### ISSUE TITLE
Cannot GET /api/v2/bestblock

### ISSUE THREAD

**Issue by atomlab** [Emurgo/yoroi-graphql-migration-backend#10]
Hi, Can I run api with debug mode? I can't understand why response  wrong.

```
$ yarn
$ npm install
$ cd ./dist
$ HASURA_URI=http://localhost:8080 node index.js
listening on 8082...
```

```
$ curl http://localhost:8082/api/v2/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/bestblock</pre>
</body>
</html>
```

```
$ curl http://localhost:8082/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /bestblock</pre>
</body>
</html>
```
Check hasura port
```
$ telnet localhost 8080
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

**Comment by SebastienGllmt** [comment]
`api/v2/bestblock` should work. I think maybe it fails if your node isn't synced though. @mebassett maybe you have an idea?

**Comment by atomlab** [comment]
@SebastienGllmt It look like node synced
```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardano { tip { number slotNo epoch { number } } } }"}' http://127.0.0.1:3100/graphql
{"data":{"cardano":{"tip":{"number":4424920,"slotNo":4427144,"epoch":{"number":204}}}}}
```

I expect an `api` write some message to stdout if something wrong with backends (graphql-hasura/graphql)

**Comment by mebassett** [comment]
@atomlab  you're correct, the error is due to the node not being synced.  

it's a _feature_ of cardano-db-sync, or at least a specified behavior (see https://github.com/input-output-hk/cardano-db-sync/blob/91aa8e1fb49f8287a567c2092ea9c84379a85b70/cardano-db-sync/src/Cardano/DbSync/Plugin/Epoch.hs#L53).  Unfortunately, when this happens, the rest of the dependency chain can't see the reason.  Hasura, et cetera, cannot tell that cardano-db-sync is still syncing or that something more sinister is going on.  So it is quite hard to come up with a specific error message, but I'll see what I can do.

**Comment by atomlab** [comment]
This is strange. 

`syncPercentage":100`
```
root@cardano-01:~# curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardanoDbMeta { initialized syncPercentage slotDiffFromNetworkTip }}"}' http://localhost:3100/graphql
{"data":{"cardanoDbMeta":{"initialized":true,"syncPercentage":100,"slotDiffFromNetworkTip":0}}}
root@cardano-01:~#
root@cardano-01:~#
root@cardano-01:~# curl http://localhost:8082/api/v2/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/bestblock</pre>
</body>
</html>
root@cardano-01:~#
root@cardano-01:~#
```

`api` logs contains only message
```
listening on 8082...
```

**Comment by SebastienGllmt** [comment]
Hmm strange. We have no idea what else could be causing this. Do you still get an issue with the `history` endpoint? I believe the history endpoint goes directly to cardano-db-sync and doesn't hit graphql at all so if that one works, then probably it's a graphql issue.

**Comment by mebassett** [comment]
Apologies for the delay, I had investigated this but other priorities took over before I could confirm.  This error occurs on new versions of cardano-graphql.   It works on, e.g., commit 688fcb0292d6f726d572396ce39da51452043a65.  but I get this error on=, e.g., 43d2d95b01c0c914af12f8f1cecedbea5a04595d.  The reason is that `blockHeight` was deprecated from the graphql definitions for cardano.  I will get this repo synced with upstream shortly and close this issue when I do.

**Comment by atomlab** [comment]
I have build last version of yoroi-graphql-migration-backend from `master-98a0ada`.

```
docker.io/inputoutput/cardano-node:1.19.0
docker.io/library/postgres:11.5-alpine
docker.io/inputoutput/cardano-graphql:2.0.0
docker.io/inputoutput/cardano-db-sync:3.1.0
docker.io/inputoutput/cardano-explorer-api:2.1.2
yoroi-graphql-migration-backend:master-98a0ada-7
```

get `/api/v2/bestblock`
```
# curl http://localhost:8082/api/v2/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/bestblock</pre>
</body>
</html>
```

`yoroi-graphql-migration-backend` logs
```
> yoroi-be-mk3@1.0.0 dev /opt/app
> tsc-watch --onSuccess "node ./dist/index.js"
12:12:08 PM - Starting compilation in watch mode...


12:12:10 PM - Found 0 errors. Watching for file changes.
listening on 8082...
(node:40) UnhandledPromiseRejectionWarning: Error: connect ENOENT /tmp//.s.PGSQL.5432
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

check `cardano-graphql` port from yoroi container
```
# podman exec -it yoroi-graphql-migration-backend bash
root@cardano:/opt/app/dist# telnet localhost 3100
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```

`cardano-graphql` logs
```
# podman logs -f cardano-graphql
GraphQL HTTP server at http://localhost:3100/
```

Last block from cardano-exporer ok
```
# curl http://localhost:8100/api/blocks/pages
{"Right":[463886,[{"cbeEpoch":214,"cbeSlot":395552,"cbeBlkHeight":4638860,"cbeBlkHash":"37519762e65269b0a860077c58962ec9494a38a64af8665c33f11de4b9f83bdb"...
```

How can I debug this `yoroi` error?

**Comment by mebassett** [comment]
The instructive bit here is the yoroi-graphql-migration-backend logs, particularly 
```
UnhandledPromiseRejectionWarning: Error: connect ENOENT /tmp//.s.PGSQL.5432
```
You likely need to edit the config (see https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/master/config/default.ts) to direct it to your postgresql database.  I do not know the exact config details for using `docker.io/library/postgres:11.5-alpine`, but it is likely over tcp rather than unix sockets,

**Comment by atomlab** [comment]
> The instructive bit here is the yoroi-graphql-migration-backend logs, particularly
> 
> ```
> UnhandledPromiseRejectionWarning: Error: connect ENOENT /tmp//.s.PGSQL.5432
> ```
> 
> You likely need to edit the config (see https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/master/config/default.ts) to direct it to your postgresql database. I do not know the exact config details for using `docker.io/library/postgres:11.5-alpine`, but it is likely over tcp rather than unix sockets,

Thank you for reply.  I have fix `default.ts` config
```
export default { 
    db: {
      user: 'cardano',
      database: 'cexplorer',
      password: 'cardano',
      host: '127.0.0.1'
    },
    server: {
      addressRequestLimit: 50,
      apiResponseLimit: 50,
      graphqlEndpoint: 'http://localhost:3100/',
      txSubmissionEndpoint: 'https://backend.yoroiwallet.com/api/submit/tx',
      smashEndpoint: 'https://smash.yoroiwallet.com/api/v1/metadata/',
      port: 8082,
      txsHashesRequestLimit: 150
    }
  }
```

`yoroi` connected to database without any errors
```
root@cardano-rest-04:/opt/cardano/yoroi-backend/config# podman logs -f yoroi

> yoroi-be-mk3@1.0.0 dev /opt/app
> tsc-watch --onSuccess "node ./dist/index.js"
5:30:55 PM - Starting compilation in watch mode...


5:30:58 PM - Found 0 errors. Watching for file changes.
listening on 8082...


^C
#
```

get request
```
# curl http://localhost:8082/api/v2/bestblock
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/bestblock</pre>
</body>
</html>
root@cardano-rest-04:/opt/cardano/yoroi-backend/config#
```

still no errors

```
`yoroi` connected to database without any errors
```
root@cardano-rest-04:/opt/cardano/yoroi-backend/config# podman logs -f yoroi

> yoroi-be-mk3@1.0.0 dev /opt/app
> tsc-watch --onSuccess "node ./dist/index.js"
5:30:55 PM - Starting compilation in watch mode...


5:30:58 PM - Found 0 errors. Watching for file changes.
listening on 8082..
```
