### ISSUE TITLE
utxoSumForAddress is not correct

### ISSUE THREAD

**Issue by matyushkins** [Emurgo/yoroi-graphql-migration-backend#185]
HI.
https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/4f6316d595cf03e70965e1f905bfbf2bb8cdd32b/src/services/utxoSumForAddress.ts#L19

The counting is not correct. You are returning the first row. but you need to summarize everything.

**Comment by matyushkins** [comment]
Or sql exemple:
`    SELECT SUM("public"."utxo_view"."value") AS "value"
    FROM "public"."utxo_view"
    WHERE "public"."utxo_view"."address" = any(($1)::varchar array)
`

**Comment by SebastienGllmt** [comment]
We don't use this endpoint for any of our projects and so this endpoint has multiple issues in it I think. We've talked about removing this endpoint in the past since it's not updated, but never got around to it.

**Comment by matyushkins** [comment]
Alternative to balance or amount uxto? if you are going to delete this point.

**Comment by SebastienGllmt** [comment]
We use `utxoForAddresses` instead

**Comment by matyushkins** [comment]
Ok
