### ISSUE TITLE
Make `cbor` vs `content-type` configurable via env variables (next to `TX_SUBMISSION_ENDPOINT`)

### ISSUE THREAD

**Issue by romang-at-guarda-co** [Emurgo/yoroi-graphql-migration-backend#264]
Content type for transaction submission is now hardcoded and changes between revisions by commenting/uncommenting these lines:

https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/a0304d48da9d81c7c9ed976c52e1f99d67b167e8/src/services/signedTransaction.ts#L7-L8

It instead should be configurable via an environment variable.

**Comment by vsubhuman** [comment]
Yup, good point, it sholda. We'll look into it

**Comment by vsubhuman** [comment]
The env variable `TX_SUBMIT_CONTENT_TYPE` can be set now, expected values are `cbor` or `octet-stream`. Default value is `octet-stream`, so makes sense setting it to `cbor` if using cardano-submit-api.

NOTE: that the `application/` prefix is hardcoded, so only need to set the env var to the string value like `"cbor"` for the final header to be `application/cbor`
