### ISSUE TITLE
Add datum hash to tx output

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-graphql-migration-backend#307]
Currently the backend doesn't support getting the datum hash associated with an output (i.e. it's missing from [here](https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/master/src/Transactions/output.ts#L5)). It should be simple enough to add this since it's simply inlined into the tx_out table in db-sync [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/schema.md#tx_out)

**Comment by JakubSmahovsky** [comment]
Working on this (can't assign myself, because we're from outside Emurgo).
